### ISSUE TITLE
Table hover is still bright.

### ISSUE THREAD

**Issue by danneu** [danneu/darkstrap#3]
``` css
.table tbody tr:hover td, .table tbody tr:hover th {
    background-color: #F5F5F5;
}
```

Needs to be darkened.
